---
siteTitle: "accu:rate"
pagetitle: Directory wide title 
creator: "Florian Sesser, accu:rate"
publisher: "accu:rate Institute for Crowd Simulation"
rights: "2014, 2015 accu-rate GbR"
baseurl: 
template: accu-rate
area:
    navigation: ../source/area/navigation.md
    sidebar: ../source/area/sidebar.md 
    footer: ../source/area/footer.md
cssversion: v9fed
jsversion: vfc53
comment: false
description: "accu:rate Institute for Crowd Simulation"
lang: de
keywords: personenstrom,simulation,fußgänger,versammlungsstätte,entfluchtung,location,event,veranstaltung,konzert,festival,altbestand,entfluchtungsnachweis,evakuierungsnachweis,evakuierungssimulation,sondernutzung,sicherheitskonzept,räumungskonzept,veranstaltungssicherheit,betreiber,risikominimierung,evakuierungsplanung,sicherheitsnachweis
---
