---
siteTitle: "accu:rate"
pagetitle: Directory wide title 
creator: "Florian Sesser, accu:rate"
publisher: "accu:rate GmbH Institute for Crowd Simulation"
rights: "2014- accu:rate"
baseurl: 
template: accu-rate
area:
    navigation: ../source/area/navigation.md
    sidebar: ../source/area/sidebar.md 
    footer: ../source/area/footer.md
cssversion: v1e15
jsversion: vfc53
comment: false
description: "accu:rate GmbH Institute for Crowd Simulation"
lang: de
keywords: personenstromsimulation,personenstromanalyse,personenstrom,simulation,fußgänger,versammlungsstätte,entfluchtung,location,event,veranstaltung,konzert,festival,altbestand,entfluchtungsnachweis,evakuierungsnachweis,evakuierungssimulation,sondernutzung,sicherheitskonzept,räumungskonzept,veranstaltungssicherheit,betreiber,risikominimierung,evakuierungsplanung,sicherheitsnachweis,besucherzählung,großveranstaltung,sicherheitskonzept,museum,hafen,maritim,evakuierungsberechnung
---
